export const peopleTitles = {
  farmers: "Farmers",
  aggregators: "Aggregators",
  suppliers: "Suppliers",
  processors: "Processors",
  offtakers: "Offtakers",

  cooperatives: "Cooperatives",
  corporate: "Corporate",
  outgrowers: "Outgrowers",
  individuals: "Small Scale (Individuals)",
  corporate_ag: "Large Scale (Corporate)",
  extension: "Extension Services",
  mechanization: "Mechanization",
  seeds: "Seeds",
  fertilizers: "Fertilizers",
  herbicides: "Herbicides",
  small: "Small Scale (1-3 tons monthly)",
  medium: "Medium Scale (3-10 tons monthly)",
  large: "Large Scale (Above 10 tons monthly)",
  local: "Local",
  international: "International",
  logistics: "Logistics",
  researchers: "Research Institutions",
};

export const peopleIcons = {
  farmers: "people",
  aggregators: "fas fa-list",
  suppliers: "fas fa-boxes-packing",
  processors: "fas fa-microchip",
  offtakers: "fas fa-plane-departure",

  cooperatives: "fas fa-users",
  corporate: "fas fa-building-flag",
  outgrowers: "fas fa-plant-wilt",
  individuals: "fas fa-user",
  corporate_ag: "fas fa-building",
  extension: "fas fa-person-shelter",
  mechanization: "fas fa-tractor",
  seeds: "fas fa-seedling",
  fertilizers: "fas fa-flask-vial",
  herbicides: "fas fa-skull-crossbones",
  small: "people",
  medium: "people",
  large: "people",
  local: "fas fa-building",
  international: "fas fa-plane",
  logistics: "fas fa-truck-fast",
  researchers: "fas fa-book",
};

export const peopleGroups = {
  farmers: ["cooperatives", "corporate", "outgrowers"],
  aggregators: ["individuals", "corporate_ag"],
  suppliers: [
    "extension",
    "mechanization",
    "seeds",
    "fertilizers",
    "herbicides",
  ],
  processors: ["small", "medium", "large"],
  offtakers: ["local", "international"],
  logistics: [],
  researchers: [],
};
